Chore/poetry 3.0.0
Hydrospheredata/hydro-stat pull request #28
Opened 2021-07-05 09:08 UTC by Vixtir

2021-07-05 10:04 UTC, akastav commented on Dockerfile
> +COPY .git .git
COPY .git/ ./.git/

2021-07-14 10:56 UTC, KineticCookie requested changes

2021-07-14 10:56 UTC, KineticCookie commented on hydro_stat/app.py
> +    logging.setLevel(logging.DEBUG)
`log` or `logging`?

2021-07-14 10:56 UTC, KineticCookie commented on tests/test_heatmap.py
> +from statistical_report.statistical_feature_report import HeatMapData
Import without correct root package

2021-07-14 10:56 UTC, KineticCookie commented on tests/test_report.py
> +from app.statistical_report.statistical_report import StatisticalReport
IIRC, `app` is not the correct package name but `hydro_stat`

2021-07-14 12:52 UTC, merged